repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
    exclude: "\\.vscode/.*.json"
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "0.11.2"
  hooks:
  - id: pyproject-fmt

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.261'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: "23.1.0"
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy
    pass_filenames: true
    additional_dependencies:
    - types-requests

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - darglint
