name: Test tap-pulumi-cloud

on:
  push:
    branches: [main]
    paths:
    - .github/workflows/constraints.txt
    - .github/workflows/test.yml
    - tap_pulumi_cloud/**
    - tests/**
    - pyproject.toml
    - uv.lock
  pull_request:
    paths:
    - .github/workflows/constraints.txt
    - .github/workflows/test.yml
    - tap_pulumi_cloud/**
    - tests/**
    - pyproject.toml
    - uv.lock
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    outputs:
      supported-python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2.18.0
        id: baipp

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [build-package]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python-version: ${{ fromJson(needs.build-package.outputs.supported-python-versions) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Nox
      env:
        UV_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
      run: |
        uv tool install --with tox-uv tox
        tox --version

    - name: Run tests
      env:
        TAP_PULUMI_CLOUD_TOKEN: ${{ secrets.TAP_PULUMI_CLOUD_TOKEN }}
        TAP_PULUMI_CLOUD_ORGANIZATIONS: ${{ secrets.TAP_PULUMI_CLOUD_ORGANIZATIONS }}
        TAP_PULUMI_CLOUD_START_DATE: ${{ secrets.TAP_PULUMI_CLOUD_START_DATE }}
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        tox -e ${PYTHON_VERSION}

  typing:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
    - name: Run Tox
      run: >
        uvx
        --managed-python
        --with=tox-uv
        tox -e typing
